### ISSUE TITLE
I can't import the file in clip input 2 or gbx explorer

### ISSUE THREAD

**Issue by thijseno** [bigbang1112-cz/gbx#42]
GBX.NET.Exceptions.NodeNotImplementedException: Node with ID 0x74736542 is not implemented. (unknown class)
at GBX.NET.Node.GetNodeInfoFromClassId(GameBoxReader r, Nullable`1 classId, Node& node)
at GBX.NET.Node.Parse(GameBoxReader r, Nullable`1 classId, IProgress`1 progress, Boolean ignoreZeroIdChunk)
at GBX.NET.GameBoxReader.ReadNodeRef(File& nodeRefFile)
at GBX.NET.GameBoxReader.ReadNodeRef[CPlugEntRecordData]()
at GBX.NET.GameBoxReaderWriter.NodeRef[CPlugEntRecordData](CPlugEntRecordData variable)
at GBX.NET.GameBoxReaderWriter.NodeRef[CPlugEntRecordData](CPlugEntRecordData& variable, Boolean disallowOverride)
at GBX.NET.Engines.Game.CGameCtnGhost.Chunk03092000.ReadWrite(CGameCtnGhost n, GameBoxReaderWriter rw)
at GBX.NET.Chunk`1[[GBX.NET.Engines.Game.CGameCtnGhost, GBX.NET, Version=1.2.4.0, Culture=neutral, PublicKeyToken=null]].GBX.NET.IReadableWritableChunk.ReadWrite(Node n, GameBoxReaderWriter rw)
at GBX.NET.Node.CreateKnownSkippableChunk(Node node, UInt32 chunkId, Byte[] chunkData, GameBoxReader reader)
at GBX.NET.Node.ReadSkippableChunkAsync(Node node, GameBoxReader r, UInt32 chunkId, Boolean reflected, CancellationToken cancellationToken)
at GBX.NET.Node.IterateChunksAsync(Node node, GameBoxReader r, Nullable`1 previousChunkId, CancellationToken cancellationToken)
at GBX.NET.Node.ReadChunkDataAsync(GameBoxReader r, CancellationToken cancellationToken)
at GBX.NET.Node.ParseAsync(Node node, GameBoxReader r, CancellationToken cancellationToken)
at GBX.NET.Node.ParseAsync(GameBoxReader r, Nullable`1 classId, CancellationToken cancellationToken)
at GBX.NET.GameBoxReader.ReadNodeRefAsync(CancellationToken cancellationToken)
at GBX.NET.GameBoxReader.d__61`1[[GBX.NET.Engines.Game.CGameCtnGhost, GBX.NET, Version=1.2.4.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
at GBX.NET.GameBoxReader.d__79`1[[GBX.NET.Engines.Game.CGameCtnGhost, GBX.NET, Version=1.2.4.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
at GBX.NET.GameBoxReader.d__80`1[[GBX.NET.Engines.Game.CGameCtnGhost, GBX.NET, Version=1.2.4.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
at GBX.NET.Engines.Game.CGameCtnReplayRecord.Chunk03093014.ReadAsync(CGameCtnReplayRecord n, GameBoxReader r, CancellationToken cancellationToken)
at GBX.NET.Chunk`1.d__16[[GBX.NET.Engines.Game.CGameCtnReplayRecord, GBX.NET, Version=1.2.4.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
at GBX.NET.Chunk`1.d__10[[GBX.NET.Engines.Game.CGameCtnReplayRecord, GBX.NET, Version=1.2.4.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
at GBX.NET.Node.ReadWriteChunkAsync(Node node, IReadableWritableChunk chunk, GameBoxReaderWriter rw, CancellationToken cancellationToken)
at GBX.NET.Node.ReadUnskippableChunkAsync(Node node, GameBoxReader r, UInt32 chunkId, CancellationToken cancellationToken)
at GBX.NET.Node.IterateChunksAsync(Node node, GameBoxReader r, Nullable`1 previousChunkId, CancellationToken cancellationToken)
at GBX.NET.Node.ReadChunkDataAsync(GameBoxReader r, CancellationToken cancellationToken)
at GBX.NET.Node.ParseAsync(Node node, GameBoxReader r, CancellationToken cancellationToken)
at GBX.NET.GameBoxBody.ReadMainNodeAsync(Node node, GameBoxReader reader, CancellationToken cancellationToken)
at GBX.NET.GameBoxBody.ReadMainNodeAsync(Node node, Stream stream, ILogger logger, GameBoxAsyncReadAction asyncAction, GbxState state, CancellationToken cancellationToken)
at GBX.NET.GameBoxBody.ReadMainNodeAsync(Node node, Byte[] data, ILogger logger, GameBoxAsyncReadAction asyncAction, GbxState state, CancellationToken cancellationToken)
at GBX.NET.GameBoxBody.ReadMainNodeAsync(Node node, Byte[] data, Int32 uncompressedSize, ILogger logger, GameBoxAsyncReadAction asyncAction, GbxState state, CancellationToken cancellationToken)
at GBX.NET.GameBoxBody.ReadCompressedAsync(Node node, GameBoxReader reader, GameBoxAsyncReadAction asyncAction, CancellationToken cancellationToken)
at GBX.NET.GameBoxBody.ReadAsync(Node node, GameBoxHeader header, GameBoxReader reader, Boolean readUncompressedBodyDirectly, GameBoxAsyncReadAction asyncAction, CancellationToken cancellationToken)
at GBX.NET.GameBox.ParseAsync(Stream stream, Boolean readUncompressedBodyDirectly, ILogger logger, GameBoxAsyncReadAction asyncAction, CancellationToken cancellationToken)
at GbxExplorer.Client.Services.GbxService.ImportGbxAsync(IBrowserFile file, Func`2 asyncEvent, CancellationToken cancellationToken)

This is the message i got when i try to import the gbx file in gbx explorer.
When i try import in clip input 2 , for whatever reason it can't be imported.

**Comment by BigBang1112** [comment]
Should be fixed now
